[tool.autoflake]
remove-all-unused-imports = true
remove-unused-variables = true
in-place = true
ignore-init-module-imports = true
exclude = "**/migrations/*"

[tool.black]
line-length = 88
exclude = "migrations/*"

[tool.isort]
profile = "black"
line_length = 88
known_third_party = ["requests", "django", "rest_framework"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
skip = ["manage.py", "migrations", ".env"]
src_paths = ["backend", "mock"]

[tool.pylint.messages_control]
good-names = ["_", "up", "v", "rm"]
ignore-paths = '''
    .*/migrations
'''
disable = [
    "import-error",
    "line-too-long",
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring",
    "too-few-public-methods",
    "too-many-ancestors",
    "unnecessary-lambda-assignment",
]
