[tool.poetry]
name = "inferred-backend"
version = "0.1.0"
description = ""
authors = ["Rafał Łazicki <rafal.lazicki99@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
black = "^23.3.0"
isort = "^5.12.0"
autoflake = "^2.0.2"
mypy = "^1.1.1"
pytest = "^7.2.2"
django = "^4.1.7"
djangorestframework = "^3.14.0"
django-environ = "^0.10.0"
psycopg2-binary = "^2.9.5"
pylint-django = "^2.5.3"
channels = "3.0.5"
channels-redis = "^4.1.0"
django-cors-headers = "^3.14.0"
uvicorn = {extras = ["standard"], version = "^0.21.1"}
celery = "^5.2.7"
invoke = "^2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
