# Generated by Django 4.2 on 2023-04-12 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_timestamp", models.DateTimeField()),
                (
                    "dimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sensors.dimension",
                    ),
                ),
            ],
            options={
                "ordering": ["start_timestamp", "dimension"],
            },
        ),
        migrations.CreateModel(
            name="SimulationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "dimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticks",
                        to="sensors.dimension",
                    ),
                ),
                (
                    "prediction",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticks",
                        to="sensors.prediction",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp", "dimension"],
            },
        ),
        migrations.AddField(
            model_name="prediction",
            name="simulation_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sensors.simulationmodel",
            ),
        ),
        migrations.AddConstraint(
            model_name="prediction",
            constraint=models.UniqueConstraint(
                models.F("simulation_model"),
                models.F("dimension"),
                models.F("start_timestamp"),
                name="unique_simulation_prediction",
            ),
        ),
    ]
