# Generated by Django 4.2.4 on 2023-08-24 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interval", models.IntegerField()),
            ],
            options={
                "ordering": ["simulation_model", "read"],
            },
        ),
        migrations.CreateModel(
            name="SimulationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SensorRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "dimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sensors.dimension",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp", "dimension"],
            },
        ),
        migrations.CreateModel(
            name="PredictionRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("offset", models.IntegerField()),
                (
                    "prediction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sensors.prediction",
                    ),
                ),
            ],
            options={
                "ordering": ["offset", "prediction"],
            },
        ),
        migrations.AddField(
            model_name="prediction",
            name="read",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sensors.sensorread"
            ),
        ),
        migrations.AddField(
            model_name="prediction",
            name="simulation_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sensors.simulationmodel",
            ),
        ),
        migrations.AddIndex(
            model_name="sensorread",
            index=models.Index(
                fields=["timestamp", "dimension"], name="sensors_sen_timesta_a41501_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="predictionread",
            index=models.Index(
                fields=["prediction", "offset"], name="sensors_pre_predict_fd60f5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="predictionread",
            constraint=models.UniqueConstraint(
                models.F("prediction"),
                models.F("offset"),
                name="unique_prediction_read",
            ),
        ),
        migrations.AddIndex(
            model_name="prediction",
            index=models.Index(fields=["read"], name="sensors_pre_read_id_69321e_idx"),
        ),
        migrations.AddConstraint(
            model_name="prediction",
            constraint=models.UniqueConstraint(
                models.F("simulation_model"),
                models.F("read"),
                name="unique_simulation_prediction",
            ),
        ),
    ]
