# Generated by Django 4.2.3 on 2023-08-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensors", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tick",
            index=models.Index(
                fields=["timestamp", "dimension"], name="sensors_tic_timesta_5f4e2e_idx"
            ),
        ),
    ]
