# Generated by Django 4.2.5 on 2023-12-13 20:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sensors", "0006_alter_predictionread_prediction"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Dimension",
            new_name="Sensor",
        ),
    ]
