# Generated by Django 4.2.5 on 2023-12-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensors", "0007_rename_dimension_sensor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sensorread",
            options={"ordering": ["timestamp", "sensor"]},
        ),
        migrations.RemoveIndex(
            model_name="sensorread",
            name="sensors_sen_timesta_a41501_idx",
        ),
        migrations.RenameField(
            model_name="sensorread",
            old_name="dimension",
            new_name="sensor",
        ),
        migrations.AddIndex(
            model_name="sensorread",
            index=models.Index(
                fields=["timestamp", "sensor"], name="sensors_sen_timesta_e737ff_idx"
            ),
        ),
    ]
